// <auto-generated />
namespace Civionics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class refactoring_sensor_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoring_sensor_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201411032104227_refactoring_sensor_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
