// <auto-generated />
namespace Civionics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addingautoranging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingautoranging));
        
        string IMigrationMetadata.Id
        {
            get { return "201411060134206_adding-auto-ranging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
