// <auto-generated />
namespace _3900_Civionics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SensorDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SensorDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201410241920046_SensorDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
